/**
 * Copyright (c) OE2RP Team, 2021
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

class OE2BaseFood: Health abstract {
	Default {
        +NOGRAVITY;
		Inventory.PickupMessage "Picked up a O&E II base food.";
		Scale OE2ScaleFactor;
		Height 32;
		Radius 32;
	}

	States {
	Spawn:
		TNT1 A -1;
		stop;
	}
} // of class OE2BaseFood: OE2BaseItem {
