/**
 * Copyright (c) OE2RP Team, 2021
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

class OE2BaseItem: CustomInventory {
	Default {
        +NOGRAVITY;
		Height 32;
		Radius 32;
		Inventory.PickupMessage "Picked up a O&E II base item.";
		Scale OE2ScaleFactor;
	}

	States {
	Spawn:
		SPID F 5 Bright;
		SPID F 5;
		loop;
	Pickup:
		TNT1 F 0 A_Print("Pickup state isn't defined!");
		stop;
	}
} // of class OE2BaseItem: CustomInventory {
