/**
 * Copyright (c) OE2RP Team, 2021
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

class BaseCharacter: BaseDecoration abstract {
	Default {
		+SOLID;
		+FRIENDLY;
	}

	action void A_OE2RP_DoDialogue( int characterNum, int replicaNum ) {
		//CallACS( "CharacterDialogue", characterNum, replicaNum, AAPTR_GET_CONVERSATION );
	}
} // of class BaseCharacter: BaseDecoration abstract {
